- name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=KethelyE&show_icons=true&include_all_commits=true&theme=sakura
          path: generated/stats.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=KethelyE&layout=compact&langs_count=8&theme=sakura
          path: generated/languages.svg
          token: ${{ secrets.PAT_TOKEN }}
