name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # Roda todos os dias à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=KethelyE&show_icons=true&include_all_commits=true&theme=rose_pine
          path: generated/stats.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=KethelyE&layout=compact&langs_count=8&theme=rose_pine
          path: generated/languages.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub Readme Stats"
